paths:
  uploads: images
  public: /
collections_config:
  content:
    path: content
    name: Website Content
    icon: description
    url: /
    disable_url: false
    _enabled_editors:
      - visual
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  hero.title:
    label: Main Heading
    comment: The big text at the top.
    cascade: true
  hero.subtitle:
    type: text
    label: Banner Subtext
    cascade: true
  hero.image:
    label: Hero Image
    comment: The large background image at the top.
    cascade: true
  sections:
    label: Mid-Page Content
    cascade: true
    item_label: title
    structures:
      style: select
      values:
        - label: Content Section
          value:
            title: New Section
            description: Enter description here
            image: images/placeholder.jpg
  popular.items:
    label: Customer Favorites
    cascade: true
    item_label: title
timezone: Etc/UTC
ssg_name: static
