# cloudcannon.config.yml

ssg_name: static
paths:
  uploads: "images"
  public: "/"

collections_config:
  # This targets the FOLDER instead of the file. 
  # It is more stable for the sidebar.
  content:
    name: "Website Content"
    path: "content"
    icon: "description"
    output: false
    # This ensures that when they click a file in 'content', 
    # the website shows up on the right.
    preview_url: "/index.html"

_inputs:
  hero.title:
    label: "Main Heading"
    comment: "The big text at the top."
  hero.subtitle:
    label: "Banner Subtext"
    type: text
  sections:
    label: "Mid-Page Content"
    item_label: "title"
  popular.items:
    label: "Customer Favorites"
    item_label: "title"