paths:
  uploads: uploads
  static: ''
collections_config:
  content:
    path: content
    name: Main Street Bagel Cafe
    icon: 10k
    disable_url: false
    preview:
      text:
      subtext:
      icon:
      icon_color:
      icon_background_color:
      image:
      metadata:
      gallery:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
editor:
  default_path:
timezone: America/Los_Angeles
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
